[package]
authors = ["Nicolas Marshall <marshall.nicolas@gmail.com>"]
edition = "2018"
name = "kademlia-rs"
version = "0.1.0"
[dependencies]
log = "*"
rand = "*"
rust-crypto = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
